// GENERATED by web/scripts/gen-ni-tokens.mjs from app/smartbrain_3000/ni_forms/tokens.json.
// Do not edit by hand; rerun the generator after a tokens.json change.
// CLIR prims name tokens (e.g. 'viz-line'); only the painter resolves them to CSS vars.

export const NI_TOKEN_NAMES = [
  "accent",
  "accent-tint",
  "badge-line",
  "bg",
  "border",
  "border-strong",
  "danger",
  "elevated",
  "faint",
  "map-land",
  "map-stroke",
  "muted",
  "ok",
  "panel",
  "row-hi",
  "text",
  "viz-axis",
  "viz-band",
  "viz-cat-1",
  "viz-cat-2",
  "viz-cat-3",
  "viz-cat-4",
  "viz-cat-5",
  "viz-cat-6",
  "viz-cat-other",
  "viz-div-mid",
  "viz-div-neg",
  "viz-div-pos",
  "viz-dot-ring",
  "viz-fill",
  "viz-grid",
  "viz-interp",
  "viz-line",
  "viz-neg",
  "viz-now",
  "viz-now-line",
  "viz-pos",
  "viz-seq-1",
  "viz-seq-2",
  "viz-seq-3",
  "viz-seq-4",
  "viz-seq-5",
  "viz-track",
  "warn"
] as const;

export type NiTokenName = (typeof NI_TOKEN_NAMES)[number];

const NAMES_SET: ReadonlySet<string> = new Set(NI_TOKEN_NAMES);

export function isTokenName(x: unknown): x is NiTokenName {
  console.assert(NAMES_SET.size > 0, "isTokenName: token set loaded");
  return typeof x === "string" && NAMES_SET.has(x);
}

export interface NiTypeRole {
  px: number; wt: number; lh: number; tnum: boolean;
  ladder?: readonly number[];
  max_lines?: number;
}

export const NI_TYPE: Record<string, NiTypeRole> = {
  "hero": {
    "px": 31,
    "wt": 600,
    "lh": 38,
    "tnum": true,
    "ladder": [
      31,
      28,
      24,
      20
    ]
  },
  "headline": {
    "px": 25,
    "wt": 600,
    "lh": 32,
    "tnum": true,
    "ladder": [
      25,
      22,
      20,
      18
    ]
  },
  "display": {
    "px": 20,
    "wt": 600,
    "lh": 26,
    "tnum": true,
    "ladder": [
      20,
      18,
      16
    ]
  },
  "name": {
    "px": 16,
    "wt": 600,
    "lh": 22,
    "tnum": false
  },
  "row": {
    "px": 16,
    "wt": 400,
    "lh": 22,
    "tnum": true
  },
  "row-strong": {
    "px": 16,
    "wt": 600,
    "lh": 22,
    "tnum": true
  },
  "title": {
    "px": 14,
    "wt": 600,
    "lh": 18,
    "tnum": false,
    "max_lines": 2
  },
  "body": {
    "px": 14,
    "wt": 400,
    "lh": 19,
    "tnum": false
  },
  "item": {
    "px": 14,
    "wt": 500,
    "lh": 19,
    "tnum": false
  },
  "sub": {
    "px": 14,
    "wt": 400,
    "lh": 19,
    "tnum": true
  },
  "delta": {
    "px": 14,
    "wt": 500,
    "lh": 19,
    "tnum": true
  },
  "index": {
    "px": 14,
    "wt": 500,
    "lh": 19,
    "tnum": true
  },
  "meta": {
    "px": 12,
    "wt": 400,
    "lh": 16,
    "tnum": true
  },
  "badge": {
    "px": 12,
    "wt": 600,
    "lh": 16,
    "tnum": false
  },
  "footer": {
    "px": 12,
    "wt": 400,
    "lh": 16,
    "tnum": true
  },
  "label": {
    "px": 11,
    "wt": 500,
    "lh": 14,
    "tnum": true
  },
  "tick": {
    "px": 11,
    "wt": 400,
    "lh": 14,
    "tnum": true
  }
};

export const NI_VIZ = {
  "line_w": 2,
  "interp_w": 1.5,
  "grid_w": 1,
  "now_w": 1,
  "dot_r": 4,
  "dot_ring": 2,
  "now_dot_r": 4.5,
  "now_dot_ring": 2,
  "track_h": 4,
  "ref_tick_h": 14,
  "ref_tick_w": 1.5,
  "label_offset": 7,
  "plot_min_share": 0.45,
  "amplitude_min": {
    "desktop": 48,
    "phone": 36
  },
  "past_alpha": 0.45,
  "bar_gap": 2,
  "bar_end_r": 4
} as const;

/** The custom-property declarations per theme, exactly as app.css carries them. */
export const NI_CSS_DARK = `
  --ni-accent: #63b3a8;
  --ni-accent-tint: rgba(99,179,168,0.1);
  --ni-badge-line: #d9a04a;
  --ni-bg: #121212;
  --ni-border: #2c2c31;
  --ni-border-strong: #3a3a41;
  --ni-danger: #e5695e;
  --ni-elevated: #202024;
  --ni-faint: #6b6b73;
  --ni-map-land: #232327;
  --ni-map-stroke: #3a3a41;
  --ni-muted: #9c9ca4;
  --ni-ok: #4fb995;
  --ni-panel: #1a1a1d;
  --ni-row-hi: rgba(99,179,168,0.1);
  --ni-text: #e6e6e6;
  --ni-viz-axis: #9c9ca4;
  --ni-viz-band: rgba(0,0,0,0.3);
  --ni-viz-cat-1: #2aa898;
  --ni-viz-cat-2: #d95926;
  --ni-viz-cat-3: #3987e5;
  --ni-viz-cat-4: #c98500;
  --ni-viz-cat-5: #d55181;
  --ni-viz-cat-6: #9085e9;
  --ni-viz-cat-other: #6b6b73;
  --ni-viz-div-mid: #383835;
  --ni-viz-div-neg: #e66767;
  --ni-viz-div-pos: #3987e5;
  --ni-viz-dot-ring: #1a1a1d;
  --ni-viz-fill: rgba(99,179,168,0.16);
  --ni-viz-grid: #2c2c31;
  --ni-viz-interp: rgba(99,179,168,0.55);
  --ni-viz-line: #63b3a8;
  --ni-viz-neg: #e5695e;
  --ni-viz-now: #e6e6e6;
  --ni-viz-now-line: #9c9ca4;
  --ni-viz-pos: #4fb995;
  --ni-viz-seq-1: #184f95;
  --ni-viz-seq-2: #256abf;
  --ni-viz-seq-3: #3987e5;
  --ni-viz-seq-4: #6da7ec;
  --ni-viz-seq-5: #9ec5f4;
  --ni-viz-track: #2c2c31;
  --ni-warn: #d9a04a;
`;

export const NI_CSS_LIGHT = `
  --ni-accent: #0e7269;
  --ni-accent-tint: rgba(14,114,105,0.07);
  --ni-badge-line: #8a5f18;
  --ni-bg: #fafaf8;
  --ni-border: #e3e3df;
  --ni-border-strong: #cfcfc9;
  --ni-danger: #b34237;
  --ni-elevated: #ffffff;
  --ni-faint: #909097;
  --ni-map-land: #f0f0ec;
  --ni-map-stroke: #cfcfc9;
  --ni-muted: #62626a;
  --ni-ok: #1b7154;
  --ni-panel: #ffffff;
  --ni-row-hi: rgba(14,114,105,0.07);
  --ni-text: #1a1a1a;
  --ni-viz-axis: #62626a;
  --ni-viz-band: rgba(26,26,26,0.05);
  --ni-viz-cat-1: #009a88;
  --ni-viz-cat-2: #eb6834;
  --ni-viz-cat-3: #2a78d6;
  --ni-viz-cat-4: #eda100;
  --ni-viz-cat-5: #e87ba4;
  --ni-viz-cat-6: #4a3aa7;
  --ni-viz-cat-other: #94949b;
  --ni-viz-div-mid: #f0efec;
  --ni-viz-div-neg: #e34948;
  --ni-viz-div-pos: #2a78d6;
  --ni-viz-dot-ring: #ffffff;
  --ni-viz-fill: rgba(14,114,105,0.12);
  --ni-viz-grid: #e3e3df;
  --ni-viz-interp: rgba(14,114,105,0.55);
  --ni-viz-line: #0e7269;
  --ni-viz-neg: #b34237;
  --ni-viz-now: #1a1a1a;
  --ni-viz-now-line: #62626a;
  --ni-viz-pos: #1b7154;
  --ni-viz-seq-1: #cde2fb;
  --ni-viz-seq-2: #86b6ef;
  --ni-viz-seq-3: #3987e5;
  --ni-viz-seq-4: #1c5cab;
  --ni-viz-seq-5: #0d366b;
  --ni-viz-track: #e3e3df;
  --ni-warn: #8a5f18;
`;
