// Build-time docs: render /docs/*.md to HTML and emit src/lib/docs.generated.ts.
//
// The same Markdown files are the public docs (rendered on GitHub) AND the
// in-app /help content — one source of truth. Rendering happens at BUILD time so
// the shipped app needs no Markdown library and the HTML stays CSP-safe (it is
// injected as static DOM, never executed). Input is our own trusted docs.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { marked } from "marked";

const here = dirname(fileURLToPath(import.meta.url));
const docsDir = join(here, "..", "..", "docs"); // web/scripts -> repo root /docs
const outFile = join(here, "..", "src", "lib", "docs.generated.ts");

const files = readdirSync(docsDir)
  .filter((f) => f.endsWith(".md") && f.toLowerCase() !== "readme.md")
  .sort(); // numeric filename prefixes (01-, 02-, …) drive ordering

// Inter-doc links are written as relative ".md" (correct on GitHub). In the app
// these become same-page "#slug" anchors so they switch sections client-side and
// stay keyboard-accessible (no JS click handler needed). The negative lookahead
// keeps ABSOLUTE links (https:, /, mailto:, existing #) untouched — e.g. a link
// to the GitHub SECURITY.md must not collapse to "#SECURITY".
const toHashLink = (html) =>
  html.replace(
    /href="(?!https?:|\/|#|mailto:)[^"]*?(?:\d+[-_])?([a-z0-9-]+)\.md(?:#[^"]*)?"/gi,
    'href="#$1"',
  );

const sections = files.map((file) => {
  const md = readFileSync(join(docsDir, file), "utf8");
  const h1 = md.match(/^#\s+(.+)$/m);
  const title = (h1 ? h1[1] : file.replace(/\.md$/, "")).trim();
  const slug = file.replace(/^\d+[-_]?/, "").replace(/\.md$/, "");
  return { slug, title, html: toHashLink(marked.parse(md)) };
});

// Fail the build on an empty docs set (the /help page assumes >=1 section) and
// on anything that isn't safe static HTML — even though we control /docs, this
// stops a future docs change from slipping a <script>/<iframe> or javascript:
// URL into content that gets injected with {@html}.
if (sections.length === 0) {
  throw new Error(`docs: no Markdown sections found in ${docsDir}`);
}
const DISALLOWED = /<\s*(?:script|iframe|object|embed)\b|(?:href|src)\s*=\s*"\s*(?:javascript|vbscript):/i;
for (const section of sections) {
  if (DISALLOWED.test(section.html)) {
    throw new Error(`docs: section '${section.slug}' contains disallowed HTML (script/iframe/object/embed or javascript: URL)`);
  }
}

const banner = "// GENERATED by web/scripts/build-docs.mjs from /docs — do not edit by hand.\n";
const body = `export interface DocSection { slug: string; title: string; html: string; }\n` +
  `export const docs: DocSection[] = ${JSON.stringify(sections, null, 2)};\n`;
writeFileSync(outFile, banner + body);
console.log(`docs: rendered ${sections.length} section(s) -> ${outFile}`);
