// Vendor the app's icon subset from the lucide package (ISC) into src/lib/icons.ts.
// Build-time only — lucide is a devDependency; the app ships plain path data with no
// runtime icon dependency. Rerun after editing SUBSET: node scripts/gen-icons.mjs
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { icons } from "lucide";

// kebab name (ours) -> candidate lucide exports, newest name first (lucide renames icons
// across majors; the alias list keeps our names stable).
const SUBSET = {
  "sun": ["Sun"],
  "moon": ["Moon"],
  "sun-moon": ["SunMoon"],
  "more-horizontal": ["Ellipsis", "MoreHorizontal"],
  "x": ["X"],
  "check": ["Check"],
  "chevron-down": ["ChevronDown"],
  "chevron-right": ["ChevronRight"],
  "search": ["Search"],
  "plus": ["Plus"],
  "send": ["SendHorizontal", "SendHorizonal", "Send"],
  "stop": ["Square"],
  "copy": ["Copy"],
  "refresh": ["RefreshCw"],
  "pencil": ["Pencil"],
  "trash": ["Trash2", "Trash"],
  "upload": ["Upload"],
  "download": ["Download"],
  "file": ["FileText"],
  "vault": ["Archive"],
  "link": ["Link"],
  "lock": ["Lock"],
  "shield": ["ShieldCheck"],
  "warn": ["TriangleAlert", "AlertTriangle"],
  "help": ["CircleHelp", "HelpCircle"],
  "chat": ["MessageSquare"],
  "book": ["BookOpen"],
  "tasks": ["ListChecks"],
  "clock": ["Clock"],
  "mail": ["Mail"],
  "activity": ["Activity"],
  "chart": ["ChartColumn", "BarChart3"],
  "sliders": ["SlidersHorizontal"],
  "monitor": ["Monitor"],
  "arrow-down": ["ArrowDown"],
};

const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
const serialize = (node) =>
  node
    .map(([tag, attrs, children]) => {
      const a = Object.entries(attrs ?? {}).map(([k, v]) => ` ${k}="${esc(v)}"`).join("");
      const inner = Array.isArray(children) && children.length ? serialize(children) : "";
      return inner ? `<${tag}${a}>${inner}</${tag}>` : `<${tag}${a}/>`;
    })
    .join("");

const out = {};
const missing = [];
for (const [name, candidates] of Object.entries(SUBSET)) {
  const hit = candidates.find((c) => icons[c]);
  if (!hit) { missing.push(`${name} (tried ${candidates.join(", ")})`); continue; }
  out[name] = serialize(icons[hit]);
}
if (missing.length) {
  console.error("lucide exports not found:\n  " + missing.join("\n  "));
  process.exit(1);
}

const body =
  "// GENERATED by web/scripts/gen-icons.mjs from the lucide package (ISC — see\n" +
  "// THIRD_PARTY_LICENSES.md). Do not edit by hand; edit the SUBSET there and rerun.\n" +
  "export const ICONS = {\n" +
  Object.entries(out).map(([k, v]) => `  "${k}": '${v.replace(/'/g, "\\'")}',`).join("\n") +
  "\n} as const;\n\nexport type IconName = keyof typeof ICONS;\n";
const dest = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "lib", "icons.ts");
writeFileSync(dest, body);
console.log(`icons: ${Object.keys(out).length} vendored -> src/lib/icons.ts`);
